CREATE DATABASE BolosDoJacquin

USE BolosDoJacquin

CREATE TABLE TipoUsuario(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Titulo VARCHAR(100) NOT NULL
);

CREATE TABLE Categoria(
	IdCategoria UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Nome VARCHAR(100) NOT NULL
);

CREATE TABLE Usuario(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdTipoUsuario UNIQUEIDENTIFiER FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL UNIQUE,
	Senha VARCHAR(60) NOT NULL,
	Situacao BIT NOT NULL,
	DataCadastro DATETIME NOT NULL
);

CREATE TABLE Produto(
	IdProduto UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario),
	IdCategoria UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Categoria(IdCategoria),
	Nome VARCHAR(100) NOT NULL,
	Preco DECIMAL(10,2) NOT NULL,
	ImagemUrl VARCHAR(MAX) NOT NULL,
	DescricaoCurta VARCHAR(100) NOT NULL,
	DescricaoLonga TEXT NOT NULL,
	Disponibilidade VARCHAR(100) NOT NULL,
	Situacao BIT NOT NULL
);

CREATE TABLE Avaliacao(
	IdAvaliacao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	IdProduto UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Produto(IdProduto),
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario),
	Nota DECIMAL(3,1) NOT NULL,
	Comentario VARCHAR (100) NOT NULL,
	MotivoOcultacao VARCHAR(100) NOT NULL,
	Situacao BIT NOT NULL,
	DataCriacao DATETIME NOT NULL,
	DataAlteracao DATETIME NOT NULL
);